config/routes.rb
Oneletter::Application.routes.draw do
  resources :letters

end

app/models/letter.rb
class Letter < ActiveRecord::Base
  attr_accessible :content, :recipient, :province, :address, :postcode, :published_at
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  def index
    @letters = Letter.all
  end
  
  def show
    @letter = Letter.find(params[:id])
  end
  
  def new
    @letter = Letter.new
  end
  
  def create
    @letter = Letter.new(params[:letter])
    if @letter.save
      flash[:notice] = "Successfully created letter."
      redirect_to @letter
    else
      render :action => 'new'
    end
  end
  
  def edit
    @letter = Letter.find(params[:id])
  end
  
  def update
    @letter = Letter.find(params[:id])
    if @letter.update_attributes(params[:letter])
      flash[:notice] = "Successfully updated letter."
      redirect_to @letter
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @letter = Letter.find(params[:id])
    @letter.destroy
    flash[:notice] = "Successfully destroyed letter."
    redirect_to letters_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
	<%= formtastic_stylesheet_link_tag %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/letters/_form.html.erb
<%= semantic_form_for @letter do |f| %>
  <%= f.inputs do %>
  
  <%= f.input :content, :label => "信件正文：", :as => :ckeditor %>
  <%= f.input :recipient, :label => "收件人：" %>
  <%= f.input :province, :label => "省/直辖市：" %>
  <%= f.input :address, :label => "详细地址：" %>
  <%= f.input :postcode, :label => "邮政编码：" %>
  <%= f.input :published_at, :label => "提交日期：" %>

   <%= f.buttons %>
  <% end %>
<% end %>

app/views/letters/edit.html.erb
<% title "Edit Letter" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @letter %> |
  <%= link_to "View All", letters_path %>
</p>

app/views/letters/index.html.erb
<% title "Letters" %>

<table>
  <tr>
    <th>Content</th>
    <th>Recipient</th>
    <th>Province</th>
    <th>Address</th>
    <th>Postcode</th>
    <th>Published At</th>
  </tr>
  <% for letter in @letters %>
    <tr>
      <td><%= letter.content %></td>
      <td><%= letter.recipient %></td>
      <td><%= letter.province %></td>
      <td><%= letter.address %></td>
      <td><%= letter.postcode %></td>
      <td><%= letter.published_at %></td>
      <td><%= link_to "Show", letter %></td>
      <td><%= link_to "Edit", edit_letter_path(letter) %></td>
      <td><%= link_to "Destroy", letter, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Letter", new_letter_path %></p>

app/views/letters/new.html.erb
<% title "New Letter" %>
  <%= javascript_include_tag :ckeditor %>
<%= render 'form' %>

<p><%= link_to "Back to List", letters_path %></p>

app/views/letters/show.html.erb
<% title "Letter" %>

<p>
  <strong>Content:</strong>
  <%= @letter.content %>
</p>
<p>
  <strong>Recipient:</strong>
  <%= @letter.recipient %>
</p>
<p>
  <strong>Province:</strong>
  <%= @letter.province %>
</p>
<p>
  <strong>Address:</strong>
  <%= @letter.address %>
</p>
<p>
  <strong>Postcode:</strong>
  <%= @letter.postcode %>
</p>
<p>
  <strong>Published At:</strong>
  <%= @letter.published_at %>
</p>



<p>
  <%= link_to "Edit", edit_letter_path(@letter) %> |
  <%= link_to "Destroy", @letter, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", letters_path %>
</p>